### ISSUE TITLE
consider splitting into "active" and "EOL'd" tables

### ISSUE THREAD

**Issue by froydnj** [glandium/firefox-linux-compat-matrix#4]
It looks like ~2/3 of the rows in the current table are for Linux distributions that are EOL'd (and a couple more would be added if we ran the script now).  It'd be nice to move those distros to a separate table, so one could more easily compare the capabilities of the distros we currently "support" when making decisions.

**Comment by glandium** [comment]
Kinda sorta fixed in 373751a
