### ISSUE TITLE
Missing information for recent SUSE releases

### ISSUE THREAD

**Issue by glandium** [glandium/firefox-linux-compat-matrix#8]
@msirringhaus would you mind taking a look and updating the information for openSUSE/SLES?

**Comment by cgrobertson** [comment]
Hi, @glandium, I'm helping @msirringhaus with this issue. Do you want me to post this info here in a comment?

**Comment by glandium** [comment]
Ideally a pull request would be great, but a comment would be the next best thing.

**Comment by cgrobertson** [comment]
Sorry for the inconvenience, but I'm not too familiar with pull requests and didn't have a lot of time to work on this today. For now I'll post what I have here and figure out the pull request next week when I get the remaining info.

OS, Kernel, Released, EOL, glibc, glib, gtk+3, drm
SUSE SLE-15-SP1, 4.12, Jun 2019, Jan 2021 / Jan 2024(LTS), 2.26, 2.54, 3.22, 2.4.97
SUSE SLE-15-SP2, 5.3, Jul 2020, Dec 2021 / Dec 2024(LTS), 2.26, 2.62, 3.24, 2.4.100
SUSE SLE-15-SP3, 5.3, Jun 2021, Dec 2022 / Dec 2025(LTS), 2.31, 2.62, 3.24, 2.4.104
SUSE SLE-15-SP4, 5.14, Jun 2022, 2.31, 2.70, 3.24, 2.4.107

**Comment by msirringhaus** [comment]
I'll try to issue a PR in the coming days

**Comment by glandium** [comment]
Fixed in aa4d344fac1eb5c95309bf2c76d350f50713658d. Thanks.
